# -*- coding: utf-8 -*-
"""ADU Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196-S9Z8lHkGPdjtnPf_ZVX7D-SebZmWk
"""


# Paste this entire block into a Colab cell or save as app.py
import pandas as pd
import numpy as np
from math import isfinite

import plotly.graph_objects as go
import plotly.express as px

# Use dash or jupyter_dash depending on environment
try:
    # In Colab, JupyterDash gives inline preview
    from jupyter_dash import JupyterDash
    in_notebook = True
except Exception:
    from dash import Dash
    in_notebook = False

from dash import dcc, html
import dash_bootstrap_components as dbc

# -----------------------
# 1) Data (from you)
# -----------------------
data = [
    {
        "name": "Basra Light",
        "API": 29.7,
        "sulfur": 2.85,
        "naphtha": 8.71,
        "kerosene": 12.78,
        "diesel": 25.12,
        "gasoil": 8.00,
        "reflux": 2.69
    },
    {
        "name": "Brent",
        "API": 38.0,
        "sulfur": 0.424,
        "naphtha": 10.26,
        "kerosene": 12.09,
        "diesel": 23.99,
        "gasoil": 6.69,
        "reflux": 6.24
    },
    {
        "name": "Qua Iboe",
        "API": 37.3,
        "sulfur": 0.12,
        "naphtha": 10.41,
        "kerosene": 11.81,
        "diesel": 23.76,
        "gasoil": 6.64,
        "reflux": 6.64
    },
    {
        "name": "Sokol",
        "API": 39.0,
        "sulfur": 0.162,
        "naphtha": 10.42,
        "kerosene": 11.94,
        "diesel": 24.28,
        "gasoil": 6.29,
        "reflux": 7.82
    },
    {
        "name": "DAS Blend",
        "API": 39.1,
        "sulfur": 1.140,
        "naphtha": 10.81,
        "kerosene": 11.39,
        "diesel": 23.95,
        "gasoil": 6.02,
        "reflux": 6.71
    }
]

df = pd.DataFrame(data)

# -----------------------
# 2) Derived metrics
# -----------------------
# Energy formula (engineering-style approximation you approved):
# Energy (kBtu/bbl) = 200 - 3*API + 10*Sulfur + 5*Reflux
df['energy_kBtu_bbl'] = 200 - 3*df['API'] + 10*df['sulfur'] + 5*df['reflux']

# Yield variability: difference between max and min product yields (naphtha, kerosene, diesel, gasoil)
df['yield_max'] = df[['naphtha','kerosene','diesel','gasoil']].max(axis=1)
df['yield_min'] = df[['naphtha','kerosene','diesel','gasoil']].min(axis=1)
df['yield_variability'] = df['yield_max'] - df['yield_min']

# Flexibility index (your chosen formula):
# Flexibility Index = (Yield Variability + 0.5 * Reflux) * 5
df['flex_index'] = (df['yield_variability'] + 0.5 * df['reflux']) * 5

# Round values for display
df['energy_kBtu_bbl'] = df['energy_kBtu_bbl'].round(2)
df['yield_variability'] = df['yield_variability'].round(2)
df['flex_index'] = df['flex_index'].round(2)
df['reflux'] = df['reflux'].round(2)

# -----------------------
# 3) Plotly Figures
# -----------------------
names = df['name'].tolist()

# Grouped bar: product yields
fig_yields = go.Figure()
fig_yields.add_bar(name='Naphtha', x=names, y=df['naphtha'], marker_line_width=0)
fig_yields.add_bar(name='Kerosene', x=names, y=df['kerosene'], marker_line_width=0)
fig_yields.add_bar(name='Diesel', x=names, y=df['diesel'], marker_line_width=0)
fig_yields.add_bar(name='Gas Oil', x=names, y=df['gasoil'], marker_line_width=0)
fig_yields.update_layout(barmode='group',
                         title='Product Yields (wt%) — grouped by crude',
                         yaxis_title='Yield (weight %)',
                         legend_title_text='Product',
                         margin=dict(t=50, b=60))

# Energy vs Reflux: line + markers for reflux (secondary y)
fig_energy = go.Figure()
fig_energy.add_trace(go.Scatter(x=names, y=df['energy_kBtu_bbl'], mode='lines+markers+text',
                                name='Estimated Energy (kBtu/bbl)',
                                text=df['energy_kBtu_bbl'],
                                textposition='top center'))
# Reflux as scatter on secondary y-axis
fig_energy.add_trace(go.Bar(x=names, y=df['reflux'], name='Reflux Ratio (avg)', yaxis='y2', opacity=0.6))
fig_energy.update_layout(
    title='Estimated Energy Consumption vs Reflux Ratio',
    yaxis=dict(title='Energy (kBtu/bbl)'),
    yaxis2=dict(title='Reflux Ratio', overlaying='y', side='right', showgrid=False),
    legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1),
    margin=dict(t=50, b=60)
)

# Add reflux value annotations on top of bars
for i, rv in enumerate(df['reflux']):
    fig_energy.add_annotation(x=names[i], y=rv, text=f"{rv}", yanchor='bottom', yshift=4, showarrow=False, yref='y2')

# Flexibility index bar chart
fig_flex = px.bar(df, x='name', y='flex_index', title='Flexibility Index (higher = more flexible)',
                  labels={'flex_index': 'Flexibility Index', 'name': 'Crude'})
fig_flex.update_layout(margin=dict(t=50, b=60))

# -----------------------
# 4) Dash app layout
# -----------------------
# Choose a Bootstrap theme for clean visuals
external_stylesheets = [dbc.themes.BOOTSTRAP]

if in_notebook:
    app = JupyterDash(__name__, external_stylesheets=external_stylesheets)
else:
    app = Dash(__name__, external_stylesheets=external_stylesheets)

app.title = "Crude Distillation KPI Dashboard"
server = app.server  # for deployment (gunicorn app:server)

header = dbc.Row([
    dbc.Col(html.H2("Crude Distillation KPI Dashboard — Interactive"), width=8),
    dbc.Col(html.Div([
        html.P("Datasets: Basra Light, Brent, Qua Iboe, Sokol, DAS Blend", style={"margin":"0"}),
        html.Small("Energy formula: 200 - 3*API + 10*Sulfur + 5*Reflux (kBtu/bbl)", style={"color":"#666"})
    ], style={"textAlign":"right"}), width=4)
], align='center', className="mb-3")

controls = dbc.Card(
    dbc.CardBody([
        dbc.Row([
            dbc.Col(html.Div([
                html.Label("Display options"),
                dcc.Checklist(
                    id='show-products',
                    options=[{'label':'Show product yields', 'value':'yields'},
                             {'label':'Show energy chart', 'value':'energy'},
                             {'label':'Show flex index', 'value':'flex'}],
                    value=['yields','energy','flex'],
                    inline=True
                )
            ]), width=12)
        ])
    ])
, className="mb-3")

layout = dbc.Container([
    header,
    controls,
    dbc.Row([
        dbc.Col(dcc.Graph(id='yields-graph', figure=fig_yields), md=6),
        dbc.Col(dcc.Graph(id='energy-graph', figure=fig_energy), md=6),
    ], className="mb-3"),
    dbc.Row([
        dbc.Col(dcc.Graph(id='flex-graph', figure=fig_flex), md=12)
    ]),
    dbc.Row([
        dbc.Col(html.Div([
            html.P("Notes:", style={"fontWeight":"600"}),
            html.Ul([
                html.Li("Energy and Flexibility Index are engineering approximations for KPI comparison."),
                html.Li("Reflux shown as average values (you can replace with ranges if available)."),
                html.Li("This app is ready to deploy: push to GitHub and point Render/Gunicorn to app.server")
            ])
        ]), md=12)
    ], className="mt-3")
], fluid=True)

app.layout = layout

# -----------------------
# 5) Interactivity: toggle charts on/off
# -----------------------
from dash.dependencies import Input, Output

@app.callback(
    Output('yields-graph', 'style'),
    Output('energy-graph', 'style'),
    Output('flex-graph', 'style'),
    Input('show-products', 'value')
)
def toggle_charts(selected):
    # default show all
    style_hidden = {'display':'none'}
    style_show = {}
    return (style_show if 'yields' in selected else style_hidden,
            style_show if 'energy' in selected else style_hidden,
            style_show if 'flex' in selected else style_hidden)

# -----------------------
# 6) Run server
# -----------------------
if __name__ == '__main__':
    # If you run this file directly (python app.py), it will start a local Dash server
    app.run(host='0.0.0.0', port=8050, debug=True)
